=== DanikPotter/university-projects/year 2/semester 2/database management systems/coursework 2/project/gym.xsd
<?xml version="1.0"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- custom types -->
    <xs:simpleType name = "pidType">
        <xs:restriction base="xs:string">
            <xs:length value="5"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name = "genderType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Male|Female"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name = "completedType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Yes|No"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name = "availableType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Yes|No"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- main schema -->
    <xs:element name="gym">
        <xs:complexType>
            <xs:sequence>
                <!-- staff -->
                <xs:element name="staff" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="gender" type="genderType"/>
                            <xs:element name="dateofbirth" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="deptID" type="xs:positiveInteger"/>
                            <xs:element name="supervisorID" type="xs:positiveInteger" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="staffid" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
                <!-- department -->
                <xs:element name="department" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departmentName" type="xs:string"/>
                            <xs:element name="headID" type="xs:positiveInteger"/>
                        </xs:sequence>
                        <xs:attribute name="deptID" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
                <!-- member -->
                <xs:element name="member" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="gender" type="genderType"/>
                            <xs:element name="dateofbirth" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="prog" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="progID" type="pidType"/>
                                        <xs:element name="completed" type="completedType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="memberid" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
                <!-- program -->
                <xs:element name="program" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="programName" type="xs:string"/>
                            <xs:element name="trainerID" type="xs:positiveInteger"/>
                            <xs:element name="available" type="availableType"/>
                        </xs:sequence>
                        <xs:attribute name="programID" type="pidType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- key and key reference definitions -->
        <xs:key name="staffIDkey">
            <xs:selector xpath="staff"/>
            <xs:field xpath="@staffid"/>
        </xs:key>
        <xs:keyref name="supervisorIDRef" refer="staffIDkey">
            <xs:selector xpath="staff"/>
            <xs:field xpath="supervisorID"/>
        </xs:keyref>
        <xs:keyref name="headIDRef" refer="staffIDkey">
            <xs:selector xpath="department"/>
            <xs:field xpath="headID"/>
        </xs:keyref>
        <xs:keyref name="trainerIDRef" refer="staffIDkey">
            <xs:selector xpath="program"/>
            <xs:field xpath="trainerID"/>
        </xs:keyref>
        <xs:key name="deptIDkey">
            <xs:selector xpath="department"/>
            <xs:field xpath="@deptID"/>
        </xs:key>
        <xs:keyref name="deptIDRef" refer="deptIDkey">
            <xs:selector xpath="staff"/>
            <xs:field xpath="deptID"/>
        </xs:keyref>
        <xs:key name="programIDkey">
            <xs:selector xpath="program"/>
            <xs:field xpath="@programID"/>
        </xs:key>
        <xs:keyref name="progIDRef" refer="programIDkey">
            <xs:selector xpath="member/prog"/>
            <xs:field xpath="progID"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== DanikPotter/university-projects/year 2/semester 2/database management systems/coursework 2/project/gym.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="gym.xslt"?>
<!-- <?xml-stylesheet type="text/xsl" href="gym2.xslt"?> --> 
<!-- <?xml-stylesheet type="text/xsl" href="gym3.xslt"?> -->
<!-- <?xml-stylesheet type="text/xsl" href="extra.xslt"?> -->
<gym 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gym.xsd">
	<staff staffid="1">
		<firstname>Naqeeb</firstname>
		<lastname>Naseer</lastname>
		<gender>Male</gender>
		<dateofbirth>1997-06-28</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<staff staffid="2">
		<firstname>Christian</firstname>
		<lastname>Chester</lastname>
		<gender>Male</gender>
		<dateofbirth>1995-05-27</dateofbirth>
		<deptID>1</deptID>
		<supervisorID>1</supervisorID>
	</staff>
	<staff staffid="3">
		<firstname>Bruce</firstname>
		<lastname>Tauro</lastname>
		<gender>Male</gender>
		<dateofbirth>1996-03-12</dateofbirth>
		<deptID>1</deptID>
		<supervisorID>1</supervisorID>
	</staff>
	<staff staffid="4">
		<firstname>Bilal</firstname>
		<lastname>Jama</lastname>
		<gender>Male</gender>
		<dateofbirth>1996-06-29</dateofbirth>
		<deptID>3</deptID>
	</staff>
	<staff staffid="5">
		<firstname>Daniyar</firstname>
		<lastname>Nazarbayev</lastname>
		<gender>Male</gender>
		<dateofbirth>1996-12-23</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="6">
		<firstname>Peter</firstname>
		<lastname>Griffin</lastname>
		<gender>Male</gender>
		<dateofbirth>1979-07-23</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="7">
		<firstname>Daval</firstname>
		<lastname>Anuj</lastname>
		<gender>Male</gender>
		<dateofbirth>1980-01-12</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="8">
		<firstname>Anish</firstname>
		<lastname>Deep</lastname>
		<gender>Male</gender>
		<dateofbirth>1971-11-17</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="9">
		<firstname>Lanre</firstname>
		<lastname>Kojo</lastname>
		<gender>Male</gender>
		<dateofbirth>1990-12-13</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="10">
		<firstname>Rupinder</firstname>
		<lastname>Aditya</lastname>
		<gender>Male</gender>
		<dateofbirth>1982-02-13</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="11">
		<firstname>Nsia</firstname>
		<lastname>Folami</lastname>
		<gender>Male</gender>
		<dateofbirth>1978-12-02</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="12">
		<firstname>Pankaj</firstname>
		<lastname>Singh</lastname>
		<gender>Male</gender>
		<dateofbirth>1993-11-22</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="13">
		<firstname>Rajender</firstname>
		<lastname>Alinafe</lastname>
		<gender>Male</gender>
		<dateofbirth>1983-09-09</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="14">
		<firstname>Gopinder</firstname>
		<lastname>Bhopesh</lastname>
		<gender>Male</gender>
		<dateofbirth>1961-06-27</dateofbirth>
		<deptID>2</deptID>
		<supervisorID>4</supervisorID>
	</staff>
	<staff staffid="15">
		<firstname>Shel</firstname>
		<lastname>Navin</lastname>
		<gender>Male</gender>
		<dateofbirth>1961-06-27</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="16">
		<firstname>Rakesh</firstname>
		<lastname>Rajkumar</lastname>
		<gender>Male</gender>
		<dateofbirth>1971-03-21</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="17">
		<firstname>Arthur</firstname>
		<lastname>Stone</lastname>
		<gender>Male</gender>
		<dateofbirth>1991-08-16</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="18">
		<firstname>Emma</firstname>
		<lastname>Stone</lastname>
		<gender>Female</gender>
		<dateofbirth>1987-01-19</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="19">
		<firstname>Hendrick</firstname>
		<lastname>Lawson</lastname>
		<gender>Male</gender>
		<dateofbirth>1959-11-15</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="20">
		<firstname>Kimberly</firstname>
		<lastname>Henesys</lastname>
		<gender>Female</gender>
		<dateofbirth>1970-10-17</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="21">
		<firstname>Brenda</firstname>
		<lastname>Lee</lastname>
		<gender>Female</gender>
		<dateofbirth>1989-04-10</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="22">
		<firstname>Holly</firstname>
		<lastname>Michaels</lastname>
		<gender>Female</gender>
		<dateofbirth>1981-07-11</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="23">
		<firstname>Allie</firstname>
		<lastname>Rae</lastname>
		<gender>Female</gender>
		<dateofbirth>1990-08-02</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="24">
		<firstname>Rick</firstname>
		<lastname>Grimes</lastname>
		<gender>Male</gender>
		<dateofbirth>1987-09-28</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="25">
		<firstname>Rick</firstname>
		<lastname>Morty</lastname>
		<gender>Male</gender>
		<dateofbirth>1988-10-07</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="26">
		<firstname>Jonathan</firstname>
		<lastname>Depp</lastname>
		<gender>Male</gender>
		<dateofbirth>1971-03-16</dateofbirth>
		<deptID>3</deptID>
		<supervisorID>6</supervisorID>
	</staff>
	<staff staffid="27">
		<firstname>Amber</firstname>
		<lastname>Heard</lastname>
		<gender>Female</gender>
		<dateofbirth>1965-07-20</dateofbirth>
		<deptID>4</deptID>
		<supervisorID>8</supervisorID>
	</staff>
	<staff staffid="28">
		<firstname>Paris</firstname>
		<lastname>France</lastname>
		<gender>Male</gender>
		<dateofbirth>1980-10-23</dateofbirth>
		<deptID>4</deptID>
		<supervisorID>8</supervisorID>
	</staff>
	<staff staffid="29">
		<firstname>Kaley</firstname>
		<lastname>Cringe</lastname>
		<gender>Female</gender>
		<dateofbirth>1980-03-25</dateofbirth>
		<deptID>4</deptID>
		<supervisorID>8</supervisorID>
	</staff>
	<staff staffid="30">
		<firstname>Kate</firstname>
		<lastname>Williams</lastname>
		<gender>Female</gender>
		<dateofbirth>1990-05-27</dateofbirth>
		<deptID>4</deptID>
		<supervisorID>8</supervisorID>
	</staff>
	<staff staffid="31">
		<firstname>Katey</firstname>
		<lastname>Mora</lastname>
		<gender>Female</gender>
		<dateofbirth>1970-03-01</dateofbirth>
		<deptID>4</deptID>
		<supervisorID>8</supervisorID>
	</staff>
	<staff staffid="32">
		<firstname>Elijah</firstname>
		<lastname>Michaelson</lastname>
		<gender>Male</gender>
		<dateofbirth>1965-07-20</dateofbirth>
		<deptID>4</deptID>
		<supervisorID>8</supervisorID>
	</staff>
	<staff staffid="33">
		<firstname>Jamie</firstname>
		<lastname>Oliver</lastname>
		<gender>Male</gender>
		<dateofbirth>1990-05-21</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<staff staffid="34">
		<firstname>Gordon</firstname>
		<lastname>Ramsay</lastname>
		<gender>Male</gender>
		<dateofbirth>1991-06-22</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<staff staffid="35">
		<firstname>Ramsay</firstname>
		<lastname>Bolton</lastname>
		<gender>Male</gender>
		<dateofbirth>1989-07-11</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<staff staffid="36">
		<firstname>Elon</firstname>
		<lastname>Musk</lastname>
		<gender>Male</gender>
		<dateofbirth>1990-08-12</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<staff staffid="37">
		<firstname>Stannis</firstname>
		<lastname>Baratheon</lastname>
		<gender>Male</gender>
		<dateofbirth>1960-09-20</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<staff staffid="38">
		<firstname>Jon</firstname>
		<lastname>Stark</lastname>
		<gender>Male</gender>
		<dateofbirth>1967-10-21</dateofbirth>
		<deptID>1</deptID>
	</staff>
	<department deptID="1">
		<departmentName>MMA</departmentName>
		<headID>1</headID>
	</department>
	<department deptID="2">
		<departmentName>Yoga</departmentName>
		<headID>4</headID>
	</department>
	<department deptID="3">
		<departmentName>Aquatics</departmentName>
		<headID>6</headID>
	</department>
	<department deptID="4">
		<departmentName>Fitness</departmentName>
		<headID>8</headID>
	</department>
	<department deptID="5">
		<departmentName>Maintenance</departmentName>
		<headID>11</headID>
	</department>
	<member memberid="1">
		<firstname>Andrew</firstname>
		<lastname>Blair</lastname>
		<gender>Male</gender>
		<dateofbirth>1992-08-24</dateofbirth>
		<prog>
			<progID>MMA01</progID>
			<completed>No</completed>
		</prog>
	</member>
	<member memberid="2">
		<firstname>Tristan</firstname>
		<lastname>Lee</lastname>
		<gender>Male</gender>
		<dateofbirth>1998-05-28</dateofbirth>
		<prog>
			<progID>FIT03</progID>
			<completed>No</completed>
		</prog>
	</member>
	<member memberid="3">
		<firstname>Amelia</firstname>
		<lastname>Dunn</lastname>
		<gender>Female</gender>
		<dateofbirth>1988-02-18</dateofbirth>
		<prog>
			<progID>AQU02</progID>
			<completed>Yes</completed>
		</prog>
		<prog>
			<progID>YOG01</progID>
			<completed>Yes</completed>
		</prog>
		<prog>
			<progID>AQU02</progID>
			<completed>No</completed>
		</prog>
	</member>
	<member memberid="4">
		<firstname>London</firstname>
		<lastname>Townsend</lastname>
		<gender>Male</gender>
		<dateofbirth>1988-12-27</dateofbirth>
		<prog>
			<progID>YOG02</progID>
			<completed>No</completed>
		</prog>
		<prog>
			<progID>YOG04</progID>
			<completed>Yes</completed>
		</prog>
		<prog>
			<progID>AQU01</progID>
			<completed>Yes</completed>
		</prog>
	</member>
	<member memberid="5">
		<firstname>Harper</firstname>
		<lastname>Perkins</lastname>
